/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AccountDetailsAndActionsStatusEnum.
* @enum {}
* @readonly
*/
export default class AccountDetailsAndActionsStatusEnum {
    
        /**
         * value: "COMPLETE"
         * @const
         */
        "COMPLETE" = "COMPLETE";

    
        /**
         * value: "INCOMPLETE"
         * @const
         */
        "INCOMPLETE" = "INCOMPLETE";

    
        /**
         * value: "RELINK_NEEDED"
         * @const
         */
        "RELINK_NEEDED" = "RELINK_NEEDED";

    

    /**
    * Returns a <code>AccountDetailsAndActionsStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AccountDetailsAndActionsStatusEnum} The enum <code>AccountDetailsAndActionsStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

