/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountTypeEnum from './AccountTypeEnum';
import RemoteData from './RemoteData';
import Employee from './Employee';

/**
 * The BankInfo model module.
 * @module model/BankInfo
 * @version 1.0
 */
class BankInfo {
    /**
     * Constructs a new <code>BankInfo</code>.
     * # The BankInfo Object ### Description The &#x60;BankInfo&#x60; object is used to represent the Bank Account information for an Employee. This is often referenced with an Employee object.  ### Usage Example Fetch from the &#x60;LIST BankInfo&#x60; endpoint and filter by &#x60;ID&#x60; to show all bank information.
     * @alias module:model/BankInfo
     */
    constructor() { 
        
        BankInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BankInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankInfo} obj Optional instance to populate.
     * @return {module:model/BankInfo} The populated <code>BankInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankInfo();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('employee')) {
                obj['employee'] = convertRelatedObjectToType(data['employee'], Employee);
            }
            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
            }
            if (data.hasOwnProperty('routing_number')) {
                obj['routing_number'] = ApiClient.convertToType(data['routing_number'], 'String');
            }
            if (data.hasOwnProperty('bank_name')) {
                obj['bank_name'] = ApiClient.convertToType(data['bank_name'], 'String');
            }
            if (data.hasOwnProperty('account_type')) {
                obj['account_type'] = ApiClient.convertToType(data['account_type'], AccountTypeEnum);
            }
            if (data.hasOwnProperty('remote_created_at')) {
                obj['remote_created_at'] = ApiClient.convertToType(data['remote_created_at'], 'Date');
            }
            if (data.hasOwnProperty('remote_data')) {
                obj['remote_data'] = ApiClient.convertToType(data['remote_data'], [RemoteData]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
BankInfo.prototype['id'] = undefined;

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
BankInfo.prototype['remote_id'] = undefined;

/**
 * The employee with this bank account.
 * @member {String} employee
 */
BankInfo.prototype['employee'] = undefined;

/**
 * The account number.
 * @member {String} account_number
 */
BankInfo.prototype['account_number'] = undefined;

/**
 * The routing number.
 * @member {String} routing_number
 */
BankInfo.prototype['routing_number'] = undefined;

/**
 * The bank name.
 * @member {String} bank_name
 */
BankInfo.prototype['bank_name'] = undefined;

/**
 * The bank account type
 * @member {module:model/AccountTypeEnum} account_type
 */
BankInfo.prototype['account_type'] = undefined;

/**
 * When the matching bank object was created in the third party system.
 * @member {Date} remote_created_at
 */
BankInfo.prototype['remote_created_at'] = undefined;

/**
 * @member {Array.<module:model/RemoteData>} remote_data
 */
BankInfo.prototype['remote_data'] = undefined;






export default BankInfo;

