/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class BenefitPlanTypeEnum.
* @enum {}
* @readonly
*/
export default class BenefitPlanTypeEnum {
    
        /**
         * value: "MEDICAL"
         * @const
         */
        "MEDICAL" = "MEDICAL";

    
        /**
         * value: "DENTAL"
         * @const
         */
        "DENTAL" = "DENTAL";

    
        /**
         * value: "VISION"
         * @const
         */
        "VISION" = "VISION";

    
        /**
         * value: "HSA"
         * @const
         */
        "HSA" = "HSA";

    
        /**
         * value: "FSA_MEDICAL"
         * @const
         */
        "FSA_MEDICAL" = "FSA_MEDICAL";

    
        /**
         * value: "FSA_DEPENDENT_CARE"
         * @const
         */
        "FSA_DEPENDENT_CARE" = "FSA_DEPENDENT_CARE";

    
        /**
         * value: "SIMPLE_IRA"
         * @const
         */
        "SIMPLE_IRA" = "SIMPLE_IRA";

    
        /**
         * value: "_401K"
         * @const
         */
        "_401K" = "_401K";

    
        /**
         * value: "ROTH_401K"
         * @const
         */
        "ROTH_401K" = "ROTH_401K";

    
        /**
         * value: "OTHER_NON_TAXABLE"
         * @const
         */
        "OTHER_NON_TAXABLE" = "OTHER_NON_TAXABLE";

    
        /**
         * value: "COMMUTER_TRANSIT"
         * @const
         */
        "COMMUTER_TRANSIT" = "COMMUTER_TRANSIT";

    
        /**
         * value: "COMMUTER_PARKING"
         * @const
         */
        "COMMUTER_PARKING" = "COMMUTER_PARKING";

    
        /**
         * value: "_401K_LOAN_PAYMENT"
         * @const
         */
        "_401K_LOAN_PAYMENT" = "_401K_LOAN_PAYMENT";

    
        /**
         * value: "SHORT_DISABILITY"
         * @const
         */
        "SHORT_DISABILITY" = "SHORT_DISABILITY";

    
        /**
         * value: "LONG_DISABILITY"
         * @const
         */
        "LONG_DISABILITY" = "LONG_DISABILITY";

    
        /**
         * value: "LIFE"
         * @const
         */
        "LIFE" = "LIFE";

    
        /**
         * value: "SEP_IRA"
         * @const
         */
        "SEP_IRA" = "SEP_IRA";

    
        /**
         * value: "SARSEP"
         * @const
         */
        "SARSEP" = "SARSEP";

    
        /**
         * value: "CUSTOM_TAXABLE"
         * @const
         */
        "CUSTOM_TAXABLE" = "CUSTOM_TAXABLE";

    
        /**
         * value: "_403B"
         * @const
         */
        "_403B" = "_403B";

    
        /**
         * value: "ROTH_403B"
         * @const
         */
        "ROTH_403B" = "ROTH_403B";

    
        /**
         * value: "STUDENT_LOAN"
         * @const
         */
        "STUDENT_LOAN" = "STUDENT_LOAN";

    

    /**
    * Returns a <code>BenefitPlanTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/BenefitPlanTypeEnum} The enum <code>BenefitPlanTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

