/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmploymentTypeEnum from './EmploymentTypeEnum';
import FlsaStatusEnum from './FlsaStatusEnum';
import PayCurrencyEnum from './PayCurrencyEnum';
import PayFrequencyEnum from './PayFrequencyEnum';
import PayPeriodEnum from './PayPeriodEnum';

/**
 * The CreateEmployment model module.
 * @module model/CreateEmployment
 * @version 1.0
 */
class CreateEmployment {
    /**
     * Constructs a new <code>CreateEmployment</code>.
     * # The Employment Object ### Description The &#x60;Employment&#x60; object is used to represent an employment position at a company. These are associated with the employee filling the role.
     * @alias module:model/CreateEmployment
     */
    constructor() { 
        
        CreateEmployment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateEmployment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateEmployment} obj Optional instance to populate.
     * @return {module:model/CreateEmployment} The populated <code>CreateEmployment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateEmployment();

            if (data.hasOwnProperty('job_title')) {
                obj['job_title'] = ApiClient.convertToType(data['job_title'], 'String');
            }
            if (data.hasOwnProperty('pay_rate')) {
                obj['pay_rate'] = ApiClient.convertToType(data['pay_rate'], 'Number');
            }
            if (data.hasOwnProperty('pay_period')) {
                obj['pay_period'] = ApiClient.convertToType(data['pay_period'], PayPeriodEnum);
            }
            if (data.hasOwnProperty('pay_frequency')) {
                obj['pay_frequency'] = ApiClient.convertToType(data['pay_frequency'], PayFrequencyEnum);
            }
            if (data.hasOwnProperty('pay_currency')) {
                obj['pay_currency'] = ApiClient.convertToType(data['pay_currency'], PayCurrencyEnum);
            }
            if (data.hasOwnProperty('flsa_status')) {
                obj['flsa_status'] = ApiClient.convertToType(data['flsa_status'], FlsaStatusEnum);
            }
            if (data.hasOwnProperty('effective_date')) {
                obj['effective_date'] = ApiClient.convertToType(data['effective_date'], 'Date');
            }
            if (data.hasOwnProperty('employment_type')) {
                obj['employment_type'] = ApiClient.convertToType(data['employment_type'], EmploymentTypeEnum);
            }
        }
        return obj;
    }


}

/**
 * The position's title.
 * @member {String} job_title
 */
CreateEmployment.prototype['job_title'] = undefined;

/**
 * The position's pay rate in dollars.
 * @member {Number} pay_rate
 */
CreateEmployment.prototype['pay_rate'] = undefined;

/**
 * The time period this pay rate encompasses.
 * @member {module:model/PayPeriodEnum} pay_period
 */
CreateEmployment.prototype['pay_period'] = undefined;

/**
 * The position's pay frequency.
 * @member {module:model/PayFrequencyEnum} pay_frequency
 */
CreateEmployment.prototype['pay_frequency'] = undefined;

/**
 * The position's currency code.
 * @member {module:model/PayCurrencyEnum} pay_currency
 */
CreateEmployment.prototype['pay_currency'] = undefined;

/**
 * The position's FLSA status.
 * @member {module:model/FlsaStatusEnum} flsa_status
 */
CreateEmployment.prototype['flsa_status'] = undefined;

/**
 * The position's effective date.
 * @member {Date} effective_date
 */
CreateEmployment.prototype['effective_date'] = undefined;

/**
 * The position's type of employment.
 * @member {module:model/EmploymentTypeEnum} employment_type
 */
CreateEmployment.prototype['employment_type'] = undefined;






export default CreateEmployment;

