/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RequestTypeEnum from './RequestTypeEnum';
import TimeOffStatusEnum from './TimeOffStatusEnum';
import UnitsEnum from './UnitsEnum';

/**
 * The CreateTimeOff model module.
 * @module model/CreateTimeOff
 * @version 1.0
 */
class CreateTimeOff {
    /**
     * Constructs a new <code>CreateTimeOff</code>.
     * # The TimeOff Object ### Description The &#x60;TimeOff&#x60; object is used to represent a Time Off Request filed by an employee.
     * @alias module:model/CreateTimeOff
     */
    constructor() { 
        
        CreateTimeOff.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateTimeOff</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateTimeOff} obj Optional instance to populate.
     * @return {module:model/CreateTimeOff} The populated <code>CreateTimeOff</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateTimeOff();

            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'String');
            }
            if (data.hasOwnProperty('approver')) {
                obj['approver'] = ApiClient.convertToType(data['approver'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], TimeOffStatusEnum);
            }
            if (data.hasOwnProperty('employee_note')) {
                obj['employee_note'] = ApiClient.convertToType(data['employee_note'], 'String');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = ApiClient.convertToType(data['units'], UnitsEnum);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('request_type')) {
                obj['request_type'] = ApiClient.convertToType(data['request_type'], RequestTypeEnum);
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('leave_type_id')) {
                obj['leave_type_id'] = ApiClient.convertToType(data['leave_type_id'], 'String');
            }
            if (data.hasOwnProperty('time_off_policy_id')) {
                obj['time_off_policy_id'] = ApiClient.convertToType(data['time_off_policy_id'], 'String');
            }
            if (data.hasOwnProperty('part_of_day')) {
                obj['part_of_day'] = ApiClient.convertToType(data['part_of_day'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The employee requesting time off.
 * @member {String} employee
 */
CreateTimeOff.prototype['employee'] = undefined;

/**
 * The employee approving the time off request.
 * @member {String} approver
 */
CreateTimeOff.prototype['approver'] = undefined;

/**
 * The status of this time off request.
 * @member {module:model/TimeOffStatusEnum} status
 */
CreateTimeOff.prototype['status'] = undefined;

/**
 * The status of this time off request.
 * @member {String} employee_note
 */
CreateTimeOff.prototype['employee_note'] = undefined;

/**
 * The unit of time requested.
 * @member {module:model/UnitsEnum} units
 */
CreateTimeOff.prototype['units'] = undefined;

/**
 * The number of time off units requested.
 * @member {Number} amount
 */
CreateTimeOff.prototype['amount'] = undefined;

/**
 * The type of time off request.
 * @member {module:model/RequestTypeEnum} request_type
 */
CreateTimeOff.prototype['request_type'] = undefined;

/**
 * @member {Date} start_date
 */
CreateTimeOff.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
CreateTimeOff.prototype['end_date'] = undefined;

/**
 * @member {String} leave_type_id
 */
CreateTimeOff.prototype['leave_type_id'] = undefined;

/**
 * @member {String} time_off_policy_id
 */
CreateTimeOff.prototype['time_off_policy_id'] = undefined;

/**
 * @member {String} part_of_day
 */
CreateTimeOff.prototype['part_of_day'] = undefined;






export default CreateTimeOff;

