/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryEnum from './CountryEnum';
import StateEnum from './StateEnum';

/**
 * The CreateLocation model module.
 * @module model/CreateLocation
 * @version 1.0
 */
class CreateLocation {
    /**
     * Constructs a new <code>CreateLocation</code>.
     * # The Location Object ### Description The &#x60;Location&#x60; object is used to represent a Location for a company. This is shared across many models and is referenced whenever a location is stored.
     * @alias module:model/CreateLocation
     */
    constructor() { 
        
        CreateLocation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLocation} obj Optional instance to populate.
     * @return {module:model/CreateLocation} The populated <code>CreateLocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLocation();

            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('street_1')) {
                obj['street_1'] = ApiClient.convertToType(data['street_1'], 'String');
            }
            if (data.hasOwnProperty('street_2')) {
                obj['street_2'] = ApiClient.convertToType(data['street_2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], StateEnum);
            }
            if (data.hasOwnProperty('zip_code')) {
                obj['zip_code'] = ApiClient.convertToType(data['zip_code'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], CountryEnum);
            }
        }
        return obj;
    }


}

/**
 * The location's phone number.
 * @member {String} phone_number
 */
CreateLocation.prototype['phone_number'] = undefined;

/**
 * Line 1 of the location's street address.
 * @member {String} street_1
 */
CreateLocation.prototype['street_1'] = undefined;

/**
 * Line 2 of the location's street address.
 * @member {String} street_2
 */
CreateLocation.prototype['street_2'] = undefined;

/**
 * The location's city.
 * @member {String} city
 */
CreateLocation.prototype['city'] = undefined;

/**
 * The location's state.
 * @member {module:model/StateEnum} state
 */
CreateLocation.prototype['state'] = undefined;

/**
 * The location's zip code.
 * @member {String} zip_code
 */
CreateLocation.prototype['zip_code'] = undefined;

/**
 * The location's country.
 * @member {module:model/CountryEnum} country
 */
CreateLocation.prototype['country'] = undefined;






export default CreateLocation;

