/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCompany model module.
 * @module model/CreateCompany
 * @version 1.0
 */
class CreateCompany {
    /**
     * Constructs a new <code>CreateCompany</code>.
     * # The Company Object ### Description The &#x60;Company&#x60; object is used to represent a Company.
     * @alias module:model/CreateCompany
     */
    constructor() { 
        
        CreateCompany.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateCompany</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCompany} obj Optional instance to populate.
     * @return {module:model/CreateCompany} The populated <code>CreateCompany</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCompany();

            if (data.hasOwnProperty('legal_name')) {
                obj['legal_name'] = ApiClient.convertToType(data['legal_name'], 'String');
            }
            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('eins')) {
                obj['eins'] = ApiClient.convertToType(data['eins'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The company's legal name.
 * @member {String} legal_name
 */
CreateCompany.prototype['legal_name'] = undefined;

/**
 * The company's display name.
 * @member {String} display_name
 */
CreateCompany.prototype['display_name'] = undefined;

/**
 * The company's Employer Identification Numbers.
 * @member {Array.<String>} eins
 */
CreateCompany.prototype['eins'] = undefined;






export default CreateCompany;

