/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DebugModelLogSummary model module.
 * @module model/DebugModelLogSummary
 * @version 1.0
 */
class DebugModelLogSummary {
    /**
     * Constructs a new <code>DebugModelLogSummary</code>.
     * @alias module:model/DebugModelLogSummary
     * @param url {String} 
     * @param method {String} 
     * @param status_code {Number} 
     */
    constructor(url, method, status_code) { 
        
        DebugModelLogSummary.initialize(this, url, method, status_code);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, url, method, status_code) { 
        obj['url'] = url;
        obj['method'] = method;
        obj['status_code'] = status_code;
    }

    /**
     * Constructs a <code>DebugModelLogSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DebugModelLogSummary} obj Optional instance to populate.
     * @return {module:model/DebugModelLogSummary} The populated <code>DebugModelLogSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DebugModelLogSummary();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('method')) {
                obj['method'] = ApiClient.convertToType(data['method'], 'String');
            }
            if (data.hasOwnProperty('status_code')) {
                obj['status_code'] = ApiClient.convertToType(data['status_code'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} url
 */
DebugModelLogSummary.prototype['url'] = undefined;

/**
 * @member {String} method
 */
DebugModelLogSummary.prototype['method'] = undefined;

/**
 * @member {Number} status_code
 */
DebugModelLogSummary.prototype['status_code'] = undefined;






export default DebugModelLogSummary;

