/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class EmploymentTypeEnum.
* @enum {}
* @readonly
*/
export default class EmploymentTypeEnum {
    
        /**
         * value: "FULL_TIME"
         * @const
         */
        "FULL_TIME" = "FULL_TIME";

    
        /**
         * value: "PART_TIME"
         * @const
         */
        "PART_TIME" = "PART_TIME";

    
        /**
         * value: "INTERN"
         * @const
         */
        "INTERN" = "INTERN";

    
        /**
         * value: "CONTRACTOR"
         * @const
         */
        "CONTRACTOR" = "CONTRACTOR";

    
        /**
         * value: "FREELANCE"
         * @const
         */
        "FREELANCE" = "FREELANCE";

    

    /**
    * Returns a <code>EmploymentTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/EmploymentTypeEnum} The enum <code>EmploymentTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

