/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class GroupTypeEnum.
* @enum {}
* @readonly
*/
export default class GroupTypeEnum {
    
        /**
         * value: "TEAM"
         * @const
         */
        "TEAM" = "TEAM";

    
        /**
         * value: "DEPARTMENT"
         * @const
         */
        "DEPARTMENT" = "DEPARTMENT";

    
        /**
         * value: "COST_CENTER"
         * @const
         */
        "COST_CENTER" = "COST_CENTER";

    
        /**
         * value: "BUSINESS_UNIT"
         * @const
         */
        "BUSINESS_UNIT" = "BUSINESS_UNIT";

    

    /**
    * Returns a <code>GroupTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/GroupTypeEnum} The enum <code>GroupTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

