/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReasonEnum from './ReasonEnum';

/**
 * The IgnoreCommonModel model module.
 * @module model/IgnoreCommonModel
 * @version 1.0
 */
class IgnoreCommonModel {
    /**
     * Constructs a new <code>IgnoreCommonModel</code>.
     * @alias module:model/IgnoreCommonModel
     * @param reason {module:model/ReasonEnum} 
     */
    constructor(reason) { 
        
        IgnoreCommonModel.initialize(this, reason);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, reason) { 
        obj['reason'] = reason;
    }

    /**
     * Constructs a <code>IgnoreCommonModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IgnoreCommonModel} obj Optional instance to populate.
     * @return {module:model/IgnoreCommonModel} The populated <code>IgnoreCommonModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IgnoreCommonModel();

            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], ReasonEnum);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ReasonEnum} reason
 */
IgnoreCommonModel.prototype['reason'] = undefined;

/**
 * @member {String} message
 */
IgnoreCommonModel.prototype['message'] = undefined;






export default IgnoreCommonModel;

