/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class IssueStatusEnum.
* @enum {}
* @readonly
*/
export default class IssueStatusEnum {
    
        /**
         * value: "ONGOING"
         * @const
         */
        "ONGOING" = "ONGOING";

    
        /**
         * value: "RESOLVED"
         * @const
         */
        "RESOLVED" = "RESOLVED";

    

    /**
    * Returns a <code>IssueStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/IssueStatusEnum} The enum <code>IssueStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

