/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayCurrencyEnum.
* @enum {}
* @readonly
*/
export default class PayCurrencyEnum {
    
        /**
         * value: "XUA"
         * @const
         */
        "XUA" = "XUA";

    
        /**
         * value: "AFN"
         * @const
         */
        "AFN" = "AFN";

    
        /**
         * value: "AFA"
         * @const
         */
        "AFA" = "AFA";

    
        /**
         * value: "ALL"
         * @const
         */
        "ALL" = "ALL";

    
        /**
         * value: "ALK"
         * @const
         */
        "ALK" = "ALK";

    
        /**
         * value: "DZD"
         * @const
         */
        "DZD" = "DZD";

    
        /**
         * value: "ADP"
         * @const
         */
        "ADP" = "ADP";

    
        /**
         * value: "AOA"
         * @const
         */
        "AOA" = "AOA";

    
        /**
         * value: "AOK"
         * @const
         */
        "AOK" = "AOK";

    
        /**
         * value: "AON"
         * @const
         */
        "AON" = "AON";

    
        /**
         * value: "AOR"
         * @const
         */
        "AOR" = "AOR";

    
        /**
         * value: "ARA"
         * @const
         */
        "ARA" = "ARA";

    
        /**
         * value: "ARS"
         * @const
         */
        "ARS" = "ARS";

    
        /**
         * value: "ARM"
         * @const
         */
        "ARM" = "ARM";

    
        /**
         * value: "ARP"
         * @const
         */
        "ARP" = "ARP";

    
        /**
         * value: "ARL"
         * @const
         */
        "ARL" = "ARL";

    
        /**
         * value: "AMD"
         * @const
         */
        "AMD" = "AMD";

    
        /**
         * value: "AWG"
         * @const
         */
        "AWG" = "AWG";

    
        /**
         * value: "AUD"
         * @const
         */
        "AUD" = "AUD";

    
        /**
         * value: "ATS"
         * @const
         */
        "ATS" = "ATS";

    
        /**
         * value: "AZN"
         * @const
         */
        "AZN" = "AZN";

    
        /**
         * value: "AZM"
         * @const
         */
        "AZM" = "AZM";

    
        /**
         * value: "BSD"
         * @const
         */
        "BSD" = "BSD";

    
        /**
         * value: "BHD"
         * @const
         */
        "BHD" = "BHD";

    
        /**
         * value: "BDT"
         * @const
         */
        "BDT" = "BDT";

    
        /**
         * value: "BBD"
         * @const
         */
        "BBD" = "BBD";

    
        /**
         * value: "BYN"
         * @const
         */
        "BYN" = "BYN";

    
        /**
         * value: "BYB"
         * @const
         */
        "BYB" = "BYB";

    
        /**
         * value: "BYR"
         * @const
         */
        "BYR" = "BYR";

    
        /**
         * value: "BEF"
         * @const
         */
        "BEF" = "BEF";

    
        /**
         * value: "BEC"
         * @const
         */
        "BEC" = "BEC";

    
        /**
         * value: "BEL"
         * @const
         */
        "BEL" = "BEL";

    
        /**
         * value: "BZD"
         * @const
         */
        "BZD" = "BZD";

    
        /**
         * value: "BMD"
         * @const
         */
        "BMD" = "BMD";

    
        /**
         * value: "BTN"
         * @const
         */
        "BTN" = "BTN";

    
        /**
         * value: "BOB"
         * @const
         */
        "BOB" = "BOB";

    
        /**
         * value: "BOL"
         * @const
         */
        "BOL" = "BOL";

    
        /**
         * value: "BOV"
         * @const
         */
        "BOV" = "BOV";

    
        /**
         * value: "BOP"
         * @const
         */
        "BOP" = "BOP";

    
        /**
         * value: "BAM"
         * @const
         */
        "BAM" = "BAM";

    
        /**
         * value: "BAD"
         * @const
         */
        "BAD" = "BAD";

    
        /**
         * value: "BAN"
         * @const
         */
        "BAN" = "BAN";

    
        /**
         * value: "BWP"
         * @const
         */
        "BWP" = "BWP";

    
        /**
         * value: "BRC"
         * @const
         */
        "BRC" = "BRC";

    
        /**
         * value: "BRZ"
         * @const
         */
        "BRZ" = "BRZ";

    
        /**
         * value: "BRE"
         * @const
         */
        "BRE" = "BRE";

    
        /**
         * value: "BRR"
         * @const
         */
        "BRR" = "BRR";

    
        /**
         * value: "BRN"
         * @const
         */
        "BRN" = "BRN";

    
        /**
         * value: "BRB"
         * @const
         */
        "BRB" = "BRB";

    
        /**
         * value: "BRL"
         * @const
         */
        "BRL" = "BRL";

    
        /**
         * value: "GBP"
         * @const
         */
        "GBP" = "GBP";

    
        /**
         * value: "BND"
         * @const
         */
        "BND" = "BND";

    
        /**
         * value: "BGL"
         * @const
         */
        "BGL" = "BGL";

    
        /**
         * value: "BGN"
         * @const
         */
        "BGN" = "BGN";

    
        /**
         * value: "BGO"
         * @const
         */
        "BGO" = "BGO";

    
        /**
         * value: "BGM"
         * @const
         */
        "BGM" = "BGM";

    
        /**
         * value: "BUK"
         * @const
         */
        "BUK" = "BUK";

    
        /**
         * value: "BIF"
         * @const
         */
        "BIF" = "BIF";

    
        /**
         * value: "XPF"
         * @const
         */
        "XPF" = "XPF";

    
        /**
         * value: "KHR"
         * @const
         */
        "KHR" = "KHR";

    
        /**
         * value: "CAD"
         * @const
         */
        "CAD" = "CAD";

    
        /**
         * value: "CVE"
         * @const
         */
        "CVE" = "CVE";

    
        /**
         * value: "KYD"
         * @const
         */
        "KYD" = "KYD";

    
        /**
         * value: "XAF"
         * @const
         */
        "XAF" = "XAF";

    
        /**
         * value: "CLE"
         * @const
         */
        "CLE" = "CLE";

    
        /**
         * value: "CLP"
         * @const
         */
        "CLP" = "CLP";

    
        /**
         * value: "CLF"
         * @const
         */
        "CLF" = "CLF";

    
        /**
         * value: "CNX"
         * @const
         */
        "CNX" = "CNX";

    
        /**
         * value: "CNY"
         * @const
         */
        "CNY" = "CNY";

    
        /**
         * value: "CNH"
         * @const
         */
        "CNH" = "CNH";

    
        /**
         * value: "COP"
         * @const
         */
        "COP" = "COP";

    
        /**
         * value: "COU"
         * @const
         */
        "COU" = "COU";

    
        /**
         * value: "KMF"
         * @const
         */
        "KMF" = "KMF";

    
        /**
         * value: "CDF"
         * @const
         */
        "CDF" = "CDF";

    
        /**
         * value: "CRC"
         * @const
         */
        "CRC" = "CRC";

    
        /**
         * value: "HRD"
         * @const
         */
        "HRD" = "HRD";

    
        /**
         * value: "HRK"
         * @const
         */
        "HRK" = "HRK";

    
        /**
         * value: "CUC"
         * @const
         */
        "CUC" = "CUC";

    
        /**
         * value: "CUP"
         * @const
         */
        "CUP" = "CUP";

    
        /**
         * value: "CYP"
         * @const
         */
        "CYP" = "CYP";

    
        /**
         * value: "CZK"
         * @const
         */
        "CZK" = "CZK";

    
        /**
         * value: "CSK"
         * @const
         */
        "CSK" = "CSK";

    
        /**
         * value: "DKK"
         * @const
         */
        "DKK" = "DKK";

    
        /**
         * value: "DJF"
         * @const
         */
        "DJF" = "DJF";

    
        /**
         * value: "DOP"
         * @const
         */
        "DOP" = "DOP";

    
        /**
         * value: "NLG"
         * @const
         */
        "NLG" = "NLG";

    
        /**
         * value: "XCD"
         * @const
         */
        "XCD" = "XCD";

    
        /**
         * value: "DDM"
         * @const
         */
        "DDM" = "DDM";

    
        /**
         * value: "ECS"
         * @const
         */
        "ECS" = "ECS";

    
        /**
         * value: "ECV"
         * @const
         */
        "ECV" = "ECV";

    
        /**
         * value: "EGP"
         * @const
         */
        "EGP" = "EGP";

    
        /**
         * value: "GQE"
         * @const
         */
        "GQE" = "GQE";

    
        /**
         * value: "ERN"
         * @const
         */
        "ERN" = "ERN";

    
        /**
         * value: "EEK"
         * @const
         */
        "EEK" = "EEK";

    
        /**
         * value: "ETB"
         * @const
         */
        "ETB" = "ETB";

    
        /**
         * value: "EUR"
         * @const
         */
        "EUR" = "EUR";

    
        /**
         * value: "XBA"
         * @const
         */
        "XBA" = "XBA";

    
        /**
         * value: "XEU"
         * @const
         */
        "XEU" = "XEU";

    
        /**
         * value: "XBB"
         * @const
         */
        "XBB" = "XBB";

    
        /**
         * value: "XBC"
         * @const
         */
        "XBC" = "XBC";

    
        /**
         * value: "XBD"
         * @const
         */
        "XBD" = "XBD";

    
        /**
         * value: "FKP"
         * @const
         */
        "FKP" = "FKP";

    
        /**
         * value: "FJD"
         * @const
         */
        "FJD" = "FJD";

    
        /**
         * value: "FIM"
         * @const
         */
        "FIM" = "FIM";

    
        /**
         * value: "FRF"
         * @const
         */
        "FRF" = "FRF";

    
        /**
         * value: "XFO"
         * @const
         */
        "XFO" = "XFO";

    
        /**
         * value: "XFU"
         * @const
         */
        "XFU" = "XFU";

    
        /**
         * value: "GMD"
         * @const
         */
        "GMD" = "GMD";

    
        /**
         * value: "GEK"
         * @const
         */
        "GEK" = "GEK";

    
        /**
         * value: "GEL"
         * @const
         */
        "GEL" = "GEL";

    
        /**
         * value: "DEM"
         * @const
         */
        "DEM" = "DEM";

    
        /**
         * value: "GHS"
         * @const
         */
        "GHS" = "GHS";

    
        /**
         * value: "GHC"
         * @const
         */
        "GHC" = "GHC";

    
        /**
         * value: "GIP"
         * @const
         */
        "GIP" = "GIP";

    
        /**
         * value: "XAU"
         * @const
         */
        "XAU" = "XAU";

    
        /**
         * value: "GRD"
         * @const
         */
        "GRD" = "GRD";

    
        /**
         * value: "GTQ"
         * @const
         */
        "GTQ" = "GTQ";

    
        /**
         * value: "GWP"
         * @const
         */
        "GWP" = "GWP";

    
        /**
         * value: "GNF"
         * @const
         */
        "GNF" = "GNF";

    
        /**
         * value: "GNS"
         * @const
         */
        "GNS" = "GNS";

    
        /**
         * value: "GYD"
         * @const
         */
        "GYD" = "GYD";

    
        /**
         * value: "HTG"
         * @const
         */
        "HTG" = "HTG";

    
        /**
         * value: "HNL"
         * @const
         */
        "HNL" = "HNL";

    
        /**
         * value: "HKD"
         * @const
         */
        "HKD" = "HKD";

    
        /**
         * value: "HUF"
         * @const
         */
        "HUF" = "HUF";

    
        /**
         * value: "IMP"
         * @const
         */
        "IMP" = "IMP";

    
        /**
         * value: "ISK"
         * @const
         */
        "ISK" = "ISK";

    
        /**
         * value: "ISJ"
         * @const
         */
        "ISJ" = "ISJ";

    
        /**
         * value: "INR"
         * @const
         */
        "INR" = "INR";

    
        /**
         * value: "IDR"
         * @const
         */
        "IDR" = "IDR";

    
        /**
         * value: "IRR"
         * @const
         */
        "IRR" = "IRR";

    
        /**
         * value: "IQD"
         * @const
         */
        "IQD" = "IQD";

    
        /**
         * value: "IEP"
         * @const
         */
        "IEP" = "IEP";

    
        /**
         * value: "ILS"
         * @const
         */
        "ILS" = "ILS";

    
        /**
         * value: "ILP"
         * @const
         */
        "ILP" = "ILP";

    
        /**
         * value: "ILR"
         * @const
         */
        "ILR" = "ILR";

    
        /**
         * value: "ITL"
         * @const
         */
        "ITL" = "ITL";

    
        /**
         * value: "JMD"
         * @const
         */
        "JMD" = "JMD";

    
        /**
         * value: "JPY"
         * @const
         */
        "JPY" = "JPY";

    
        /**
         * value: "JOD"
         * @const
         */
        "JOD" = "JOD";

    
        /**
         * value: "KZT"
         * @const
         */
        "KZT" = "KZT";

    
        /**
         * value: "KES"
         * @const
         */
        "KES" = "KES";

    
        /**
         * value: "KWD"
         * @const
         */
        "KWD" = "KWD";

    
        /**
         * value: "KGS"
         * @const
         */
        "KGS" = "KGS";

    
        /**
         * value: "LAK"
         * @const
         */
        "LAK" = "LAK";

    
        /**
         * value: "LVL"
         * @const
         */
        "LVL" = "LVL";

    
        /**
         * value: "LVR"
         * @const
         */
        "LVR" = "LVR";

    
        /**
         * value: "LBP"
         * @const
         */
        "LBP" = "LBP";

    
        /**
         * value: "LSL"
         * @const
         */
        "LSL" = "LSL";

    
        /**
         * value: "LRD"
         * @const
         */
        "LRD" = "LRD";

    
        /**
         * value: "LYD"
         * @const
         */
        "LYD" = "LYD";

    
        /**
         * value: "LTL"
         * @const
         */
        "LTL" = "LTL";

    
        /**
         * value: "LTT"
         * @const
         */
        "LTT" = "LTT";

    
        /**
         * value: "LUL"
         * @const
         */
        "LUL" = "LUL";

    
        /**
         * value: "LUC"
         * @const
         */
        "LUC" = "LUC";

    
        /**
         * value: "LUF"
         * @const
         */
        "LUF" = "LUF";

    
        /**
         * value: "MOP"
         * @const
         */
        "MOP" = "MOP";

    
        /**
         * value: "MKD"
         * @const
         */
        "MKD" = "MKD";

    
        /**
         * value: "MKN"
         * @const
         */
        "MKN" = "MKN";

    
        /**
         * value: "MGA"
         * @const
         */
        "MGA" = "MGA";

    
        /**
         * value: "MGF"
         * @const
         */
        "MGF" = "MGF";

    
        /**
         * value: "MWK"
         * @const
         */
        "MWK" = "MWK";

    
        /**
         * value: "MYR"
         * @const
         */
        "MYR" = "MYR";

    
        /**
         * value: "MVR"
         * @const
         */
        "MVR" = "MVR";

    
        /**
         * value: "MVP"
         * @const
         */
        "MVP" = "MVP";

    
        /**
         * value: "MLF"
         * @const
         */
        "MLF" = "MLF";

    
        /**
         * value: "MTL"
         * @const
         */
        "MTL" = "MTL";

    
        /**
         * value: "MTP"
         * @const
         */
        "MTP" = "MTP";

    
        /**
         * value: "MRU"
         * @const
         */
        "MRU" = "MRU";

    
        /**
         * value: "MRO"
         * @const
         */
        "MRO" = "MRO";

    
        /**
         * value: "MUR"
         * @const
         */
        "MUR" = "MUR";

    
        /**
         * value: "MXV"
         * @const
         */
        "MXV" = "MXV";

    
        /**
         * value: "MXN"
         * @const
         */
        "MXN" = "MXN";

    
        /**
         * value: "MXP"
         * @const
         */
        "MXP" = "MXP";

    
        /**
         * value: "MDC"
         * @const
         */
        "MDC" = "MDC";

    
        /**
         * value: "MDL"
         * @const
         */
        "MDL" = "MDL";

    
        /**
         * value: "MCF"
         * @const
         */
        "MCF" = "MCF";

    
        /**
         * value: "MNT"
         * @const
         */
        "MNT" = "MNT";

    
        /**
         * value: "MAD"
         * @const
         */
        "MAD" = "MAD";

    
        /**
         * value: "MAF"
         * @const
         */
        "MAF" = "MAF";

    
        /**
         * value: "MZE"
         * @const
         */
        "MZE" = "MZE";

    
        /**
         * value: "MZN"
         * @const
         */
        "MZN" = "MZN";

    
        /**
         * value: "MZM"
         * @const
         */
        "MZM" = "MZM";

    
        /**
         * value: "MMK"
         * @const
         */
        "MMK" = "MMK";

    
        /**
         * value: "NAD"
         * @const
         */
        "NAD" = "NAD";

    
        /**
         * value: "NPR"
         * @const
         */
        "NPR" = "NPR";

    
        /**
         * value: "ANG"
         * @const
         */
        "ANG" = "ANG";

    
        /**
         * value: "TWD"
         * @const
         */
        "TWD" = "TWD";

    
        /**
         * value: "NZD"
         * @const
         */
        "NZD" = "NZD";

    
        /**
         * value: "NIO"
         * @const
         */
        "NIO" = "NIO";

    
        /**
         * value: "NIC"
         * @const
         */
        "NIC" = "NIC";

    
        /**
         * value: "NGN"
         * @const
         */
        "NGN" = "NGN";

    
        /**
         * value: "KPW"
         * @const
         */
        "KPW" = "KPW";

    
        /**
         * value: "NOK"
         * @const
         */
        "NOK" = "NOK";

    
        /**
         * value: "OMR"
         * @const
         */
        "OMR" = "OMR";

    
        /**
         * value: "PKR"
         * @const
         */
        "PKR" = "PKR";

    
        /**
         * value: "XPD"
         * @const
         */
        "XPD" = "XPD";

    
        /**
         * value: "PAB"
         * @const
         */
        "PAB" = "PAB";

    
        /**
         * value: "PGK"
         * @const
         */
        "PGK" = "PGK";

    
        /**
         * value: "PYG"
         * @const
         */
        "PYG" = "PYG";

    
        /**
         * value: "PEI"
         * @const
         */
        "PEI" = "PEI";

    
        /**
         * value: "PEN"
         * @const
         */
        "PEN" = "PEN";

    
        /**
         * value: "PES"
         * @const
         */
        "PES" = "PES";

    
        /**
         * value: "PHP"
         * @const
         */
        "PHP" = "PHP";

    
        /**
         * value: "XPT"
         * @const
         */
        "XPT" = "XPT";

    
        /**
         * value: "PLN"
         * @const
         */
        "PLN" = "PLN";

    
        /**
         * value: "PLZ"
         * @const
         */
        "PLZ" = "PLZ";

    
        /**
         * value: "PTE"
         * @const
         */
        "PTE" = "PTE";

    
        /**
         * value: "GWE"
         * @const
         */
        "GWE" = "GWE";

    
        /**
         * value: "QAR"
         * @const
         */
        "QAR" = "QAR";

    
        /**
         * value: "XRE"
         * @const
         */
        "XRE" = "XRE";

    
        /**
         * value: "RHD"
         * @const
         */
        "RHD" = "RHD";

    
        /**
         * value: "RON"
         * @const
         */
        "RON" = "RON";

    
        /**
         * value: "ROL"
         * @const
         */
        "ROL" = "ROL";

    
        /**
         * value: "RUB"
         * @const
         */
        "RUB" = "RUB";

    
        /**
         * value: "RUR"
         * @const
         */
        "RUR" = "RUR";

    
        /**
         * value: "RWF"
         * @const
         */
        "RWF" = "RWF";

    
        /**
         * value: "SVC"
         * @const
         */
        "SVC" = "SVC";

    
        /**
         * value: "WST"
         * @const
         */
        "WST" = "WST";

    
        /**
         * value: "SAR"
         * @const
         */
        "SAR" = "SAR";

    
        /**
         * value: "RSD"
         * @const
         */
        "RSD" = "RSD";

    
        /**
         * value: "CSD"
         * @const
         */
        "CSD" = "CSD";

    
        /**
         * value: "SCR"
         * @const
         */
        "SCR" = "SCR";

    
        /**
         * value: "SLL"
         * @const
         */
        "SLL" = "SLL";

    
        /**
         * value: "XAG"
         * @const
         */
        "XAG" = "XAG";

    
        /**
         * value: "SGD"
         * @const
         */
        "SGD" = "SGD";

    
        /**
         * value: "SKK"
         * @const
         */
        "SKK" = "SKK";

    
        /**
         * value: "SIT"
         * @const
         */
        "SIT" = "SIT";

    
        /**
         * value: "SBD"
         * @const
         */
        "SBD" = "SBD";

    
        /**
         * value: "SOS"
         * @const
         */
        "SOS" = "SOS";

    
        /**
         * value: "ZAR"
         * @const
         */
        "ZAR" = "ZAR";

    
        /**
         * value: "ZAL"
         * @const
         */
        "ZAL" = "ZAL";

    
        /**
         * value: "KRH"
         * @const
         */
        "KRH" = "KRH";

    
        /**
         * value: "KRW"
         * @const
         */
        "KRW" = "KRW";

    
        /**
         * value: "KRO"
         * @const
         */
        "KRO" = "KRO";

    
        /**
         * value: "SSP"
         * @const
         */
        "SSP" = "SSP";

    
        /**
         * value: "SUR"
         * @const
         */
        "SUR" = "SUR";

    
        /**
         * value: "ESP"
         * @const
         */
        "ESP" = "ESP";

    
        /**
         * value: "ESA"
         * @const
         */
        "ESA" = "ESA";

    
        /**
         * value: "ESB"
         * @const
         */
        "ESB" = "ESB";

    
        /**
         * value: "XDR"
         * @const
         */
        "XDR" = "XDR";

    
        /**
         * value: "LKR"
         * @const
         */
        "LKR" = "LKR";

    
        /**
         * value: "SHP"
         * @const
         */
        "SHP" = "SHP";

    
        /**
         * value: "XSU"
         * @const
         */
        "XSU" = "XSU";

    
        /**
         * value: "SDD"
         * @const
         */
        "SDD" = "SDD";

    
        /**
         * value: "SDG"
         * @const
         */
        "SDG" = "SDG";

    
        /**
         * value: "SDP"
         * @const
         */
        "SDP" = "SDP";

    
        /**
         * value: "SRD"
         * @const
         */
        "SRD" = "SRD";

    
        /**
         * value: "SRG"
         * @const
         */
        "SRG" = "SRG";

    
        /**
         * value: "SZL"
         * @const
         */
        "SZL" = "SZL";

    
        /**
         * value: "SEK"
         * @const
         */
        "SEK" = "SEK";

    
        /**
         * value: "CHF"
         * @const
         */
        "CHF" = "CHF";

    
        /**
         * value: "SYP"
         * @const
         */
        "SYP" = "SYP";

    
        /**
         * value: "STN"
         * @const
         */
        "STN" = "STN";

    
        /**
         * value: "STD"
         * @const
         */
        "STD" = "STD";

    
        /**
         * value: "TVD"
         * @const
         */
        "TVD" = "TVD";

    
        /**
         * value: "TJR"
         * @const
         */
        "TJR" = "TJR";

    
        /**
         * value: "TJS"
         * @const
         */
        "TJS" = "TJS";

    
        /**
         * value: "TZS"
         * @const
         */
        "TZS" = "TZS";

    
        /**
         * value: "XTS"
         * @const
         */
        "XTS" = "XTS";

    
        /**
         * value: "THB"
         * @const
         */
        "THB" = "THB";

    
        /**
         * value: "XXX"
         * @const
         */
        "XXX" = "XXX";

    
        /**
         * value: "TPE"
         * @const
         */
        "TPE" = "TPE";

    
        /**
         * value: "TOP"
         * @const
         */
        "TOP" = "TOP";

    
        /**
         * value: "TTD"
         * @const
         */
        "TTD" = "TTD";

    
        /**
         * value: "TND"
         * @const
         */
        "TND" = "TND";

    
        /**
         * value: "TRY"
         * @const
         */
        "TRY" = "TRY";

    
        /**
         * value: "TRL"
         * @const
         */
        "TRL" = "TRL";

    
        /**
         * value: "TMT"
         * @const
         */
        "TMT" = "TMT";

    
        /**
         * value: "TMM"
         * @const
         */
        "TMM" = "TMM";

    
        /**
         * value: "USD"
         * @const
         */
        "USD" = "USD";

    
        /**
         * value: "USN"
         * @const
         */
        "USN" = "USN";

    
        /**
         * value: "USS"
         * @const
         */
        "USS" = "USS";

    
        /**
         * value: "UGX"
         * @const
         */
        "UGX" = "UGX";

    
        /**
         * value: "UGS"
         * @const
         */
        "UGS" = "UGS";

    
        /**
         * value: "UAH"
         * @const
         */
        "UAH" = "UAH";

    
        /**
         * value: "UAK"
         * @const
         */
        "UAK" = "UAK";

    
        /**
         * value: "AED"
         * @const
         */
        "AED" = "AED";

    
        /**
         * value: "UYW"
         * @const
         */
        "UYW" = "UYW";

    
        /**
         * value: "UYU"
         * @const
         */
        "UYU" = "UYU";

    
        /**
         * value: "UYP"
         * @const
         */
        "UYP" = "UYP";

    
        /**
         * value: "UYI"
         * @const
         */
        "UYI" = "UYI";

    
        /**
         * value: "UZS"
         * @const
         */
        "UZS" = "UZS";

    
        /**
         * value: "VUV"
         * @const
         */
        "VUV" = "VUV";

    
        /**
         * value: "VES"
         * @const
         */
        "VES" = "VES";

    
        /**
         * value: "VEB"
         * @const
         */
        "VEB" = "VEB";

    
        /**
         * value: "VEF"
         * @const
         */
        "VEF" = "VEF";

    
        /**
         * value: "VND"
         * @const
         */
        "VND" = "VND";

    
        /**
         * value: "VNN"
         * @const
         */
        "VNN" = "VNN";

    
        /**
         * value: "CHE"
         * @const
         */
        "CHE" = "CHE";

    
        /**
         * value: "CHW"
         * @const
         */
        "CHW" = "CHW";

    
        /**
         * value: "XOF"
         * @const
         */
        "XOF" = "XOF";

    
        /**
         * value: "YDD"
         * @const
         */
        "YDD" = "YDD";

    
        /**
         * value: "YER"
         * @const
         */
        "YER" = "YER";

    
        /**
         * value: "YUN"
         * @const
         */
        "YUN" = "YUN";

    
        /**
         * value: "YUD"
         * @const
         */
        "YUD" = "YUD";

    
        /**
         * value: "YUM"
         * @const
         */
        "YUM" = "YUM";

    
        /**
         * value: "YUR"
         * @const
         */
        "YUR" = "YUR";

    
        /**
         * value: "ZWN"
         * @const
         */
        "ZWN" = "ZWN";

    
        /**
         * value: "ZRN"
         * @const
         */
        "ZRN" = "ZRN";

    
        /**
         * value: "ZRZ"
         * @const
         */
        "ZRZ" = "ZRZ";

    
        /**
         * value: "ZMW"
         * @const
         */
        "ZMW" = "ZMW";

    
        /**
         * value: "ZMK"
         * @const
         */
        "ZMK" = "ZMK";

    
        /**
         * value: "ZWD"
         * @const
         */
        "ZWD" = "ZWD";

    
        /**
         * value: "ZWR"
         * @const
         */
        "ZWR" = "ZWR";

    
        /**
         * value: "ZWL"
         * @const
         */
        "ZWL" = "ZWL";

    

    /**
    * Returns a <code>PayCurrencyEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PayCurrencyEnum} The enum <code>PayCurrencyEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

