/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayFrequencyEnum.
* @enum {}
* @readonly
*/
export default class PayFrequencyEnum {
    
        /**
         * value: "WEEKLY"
         * @const
         */
        "WEEKLY" = "WEEKLY";

    
        /**
         * value: "BIWEEKLY"
         * @const
         */
        "BIWEEKLY" = "BIWEEKLY";

    
        /**
         * value: "MONTHLY"
         * @const
         */
        "MONTHLY" = "MONTHLY";

    
        /**
         * value: "QUARTERLY"
         * @const
         */
        "QUARTERLY" = "QUARTERLY";

    
        /**
         * value: "SEMIANNUALLY"
         * @const
         */
        "SEMIANNUALLY" = "SEMIANNUALLY";

    
        /**
         * value: "ANNUALLY"
         * @const
         */
        "ANNUALLY" = "ANNUALLY";

    
        /**
         * value: "THIRTEEN-MONTHLY"
         * @const
         */
        "THIRTEEN-MONTHLY" = "THIRTEEN-MONTHLY";

    
        /**
         * value: "PRO_RATA"
         * @const
         */
        "PRO_RATA" = "PRO_RATA";

    
        /**
         * value: "NULL"
         * @const
         */
        "NULL" = "NULL";

    

    /**
    * Returns a <code>PayFrequencyEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PayFrequencyEnum} The enum <code>PayFrequencyEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

