/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayPeriodEnum.
* @enum {}
* @readonly
*/
export default class PayPeriodEnum {
    
        /**
         * value: "HOUR"
         * @const
         */
        "HOUR" = "HOUR";

    
        /**
         * value: "DAY"
         * @const
         */
        "DAY" = "DAY";

    
        /**
         * value: "WEEK"
         * @const
         */
        "WEEK" = "WEEK";

    
        /**
         * value: "EVERY_TWO_WEEKS"
         * @const
         */
        "EVERY_TWO_WEEKS" = "EVERY_TWO_WEEKS";

    
        /**
         * value: "MONTH"
         * @const
         */
        "MONTH" = "MONTH";

    
        /**
         * value: "QUARTER"
         * @const
         */
        "QUARTER" = "QUARTER";

    
        /**
         * value: "EVERY_SIX_MONTHS"
         * @const
         */
        "EVERY_SIX_MONTHS" = "EVERY_SIX_MONTHS";

    
        /**
         * value: "YEAR"
         * @const
         */
        "YEAR" = "YEAR";

    

    /**
    * Returns a <code>PayPeriodEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PayPeriodEnum} The enum <code>PayPeriodEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

