/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RemoteData from './RemoteData';
import RunStateEnum from './RunStateEnum';
import RunTypeEnum from './RunTypeEnum';

/**
 * The PayrollRun model module.
 * @module model/PayrollRun
 * @version 1.0
 */
class PayrollRun {
    /**
     * Constructs a new <code>PayrollRun</code>.
     * # The PayrollRun Object ### Description The &#x60;PayrollRun&#x60; object is used to represent a payroll run.  ### Usage Example Fetch from the &#x60;LIST PayrollRuns&#x60; endpoint and filter by &#x60;ID&#x60; to show all payroll runs.
     * @alias module:model/PayrollRun
     */
    constructor() { 
        
        PayrollRun.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayrollRun</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayrollRun} obj Optional instance to populate.
     * @return {module:model/PayrollRun} The populated <code>PayrollRun</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayrollRun();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('run_state')) {
                obj['run_state'] = ApiClient.convertToType(data['run_state'], RunStateEnum);
            }
            if (data.hasOwnProperty('run_type')) {
                obj['run_type'] = ApiClient.convertToType(data['run_type'], RunTypeEnum);
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
            if (data.hasOwnProperty('check_date')) {
                obj['check_date'] = ApiClient.convertToType(data['check_date'], 'Date');
            }
            if (data.hasOwnProperty('remote_data')) {
                obj['remote_data'] = ApiClient.convertToType(data['remote_data'], [RemoteData]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
PayrollRun.prototype['id'] = undefined;

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
PayrollRun.prototype['remote_id'] = undefined;

/**
 * The state of the payroll run
 * @member {module:model/RunStateEnum} run_state
 */
PayrollRun.prototype['run_state'] = undefined;

/**
 * The type of the payroll run
 * @member {module:model/RunTypeEnum} run_type
 */
PayrollRun.prototype['run_type'] = undefined;

/**
 * The day and time the payroll run started.
 * @member {Date} start_date
 */
PayrollRun.prototype['start_date'] = undefined;

/**
 * The day and time the payroll run ended.
 * @member {Date} end_date
 */
PayrollRun.prototype['end_date'] = undefined;

/**
 * The day and time the payroll run was checked.
 * @member {Date} check_date
 */
PayrollRun.prototype['check_date'] = undefined;

/**
 * @member {Array.<module:model/RemoteData>} remote_data
 */
PayrollRun.prototype['remote_data'] = undefined;






export default PayrollRun;

