/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoteKeyForRegenerationRequest model module.
 * @module model/RemoteKeyForRegenerationRequest
 * @version 1.0
 */
class RemoteKeyForRegenerationRequest {
    /**
     * Constructs a new <code>RemoteKeyForRegenerationRequest</code>.
     * # The RemoteKeyForRegeneration Object ### Description The &#x60;RemoteKeyForRegeneration&#x60; object is used to exchange an old remote key for a new one  ### Usage Example Post a &#x60;RemoteKeyForRegeneration&#x60; to swap out an old remote key for a new one
     * @alias module:model/RemoteKeyForRegenerationRequest
     * @param name {String} 
     */
    constructor(name) { 
        
        RemoteKeyForRegenerationRequest.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>RemoteKeyForRegenerationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoteKeyForRegenerationRequest} obj Optional instance to populate.
     * @return {module:model/RemoteKeyForRegenerationRequest} The populated <code>RemoteKeyForRegenerationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoteKeyForRegenerationRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
RemoteKeyForRegenerationRequest.prototype['name'] = undefined;






export default RemoteKeyForRegenerationRequest;

