/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class RunTypeEnum.
* @enum {}
* @readonly
*/
export default class RunTypeEnum {
    
        /**
         * value: "INIT"
         * @const
         */
        "INIT" = "INIT";

    
        /**
         * value: "REGULAR"
         * @const
         */
        "REGULAR" = "REGULAR";

    
        /**
         * value: "OFF_CYCLE"
         * @const
         */
        "OFF_CYCLE" = "OFF_CYCLE";

    
        /**
         * value: "CORRECTION"
         * @const
         */
        "CORRECTION" = "CORRECTION";

    
        /**
         * value: "TERMINATION"
         * @const
         */
        "TERMINATION" = "TERMINATION";

    
        /**
         * value: "RECONCILIATION"
         * @const
         */
        "RECONCILIATION" = "RECONCILIATION";

    
        /**
         * value: "NEW_HIRE"
         * @const
         */
        "NEW_HIRE" = "NEW_HIRE";

    
        /**
         * value: "POP"
         * @const
         */
        "POP" = "POP";

    
        /**
         * value: "TRANSITION"
         * @const
         */
        "TRANSITION" = "TRANSITION";

    
        /**
         * value: "CORRECTION_DISPLAY"
         * @const
         */
        "CORRECTION_DISPLAY" = "CORRECTION_DISPLAY";

    
        /**
         * value: "EXCESS_HOURS"
         * @const
         */
        "EXCESS_HOURS" = "EXCESS_HOURS";

    
        /**
         * value: "SIGN_ON_BONUS"
         * @const
         */
        "SIGN_ON_BONUS" = "SIGN_ON_BONUS";

    
        /**
         * value: "S_CORP"
         * @const
         */
        "S_CORP" = "S_CORP";

    
        /**
         * value: "FRINGE_BENEFITS"
         * @const
         */
        "FRINGE_BENEFITS" = "FRINGE_BENEFITS";

    
        /**
         * value: "CONTRACTOR_LATE_PAYMENTS"
         * @const
         */
        "CONTRACTOR_LATE_PAYMENTS" = "CONTRACTOR_LATE_PAYMENTS";

    

    /**
    * Returns a <code>RunTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RunTypeEnum} The enum <code>RunTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

