/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tax model module.
 * @module model/Tax
 * @version 1.0
 */
class Tax {
    /**
     * Constructs a new <code>Tax</code>.
     * # The Tax Object ### Description The &#x60;Tax&#x60; object is used to represent a tax for a given employee&#39;s payroll run. One run could include several taxes.  ### Usage Example Fetch from the &#x60;LIST Taxes&#x60; endpoint and filter by &#x60;ID&#x60; to show all taxes.
     * @alias module:model/Tax
     */
    constructor() { 
        
        Tax.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Tax</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tax} obj Optional instance to populate.
     * @return {module:model/Tax} The populated <code>Tax</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tax();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('employee_payroll_run')) {
                obj['employee_payroll_run'] = ApiClient.convertToType(data['employee_payroll_run'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('employer_tax')) {
                obj['employer_tax'] = ApiClient.convertToType(data['employer_tax'], 'Boolean');
            }
            if (data.hasOwnProperty('remote_data')) {
                obj['remote_data'] = ApiClient.convertToType(data['remote_data'], [{'String': Object}]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
Tax.prototype['id'] = undefined;

/**
 * The tax's employee payroll run.
 * @member {String} employee_payroll_run
 */
Tax.prototype['employee_payroll_run'] = undefined;

/**
 * The tax's name.
 * @member {String} name
 */
Tax.prototype['name'] = undefined;

/**
 * The tax amount.
 * @member {Number} amount
 */
Tax.prototype['amount'] = undefined;

/**
 * Whether or not the employer is responsible for paying the tax.
 * @member {Boolean} employer_tax
 */
Tax.prototype['employer_tax'] = undefined;

/**
 * @member {Array.<Object.<String, Object>>} remote_data
 */
Tax.prototype['remote_data'] = undefined;






export default Tax;

