/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AccountDetails from '../model/AccountDetails';

/**
* AccountDetails service.
* @module api/AccountDetailsApi
* @version 1.0
*/
export default class AccountDetailsApi {

    /**
    * Constructs a new AccountDetailsApi. 
    * @alias module:api/AccountDetailsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the accountDetailsRetrieve operation.
     * @callback module:api/AccountDetailsApi~accountDetailsRetrieveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AccountDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details for a linked account.
     * @param {String} x_account_token Token identifying the end user.
     * @param {module:api/AccountDetailsApi~accountDetailsRetrieveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AccountDetails}
     */
    accountDetailsRetrieve(x_account_token, callback) {
      let postBody = null;
      // verify the required parameter 'x_account_token' is set
      if (x_account_token === undefined || x_account_token === null) {
        throw new Error("Missing the required parameter 'x_account_token' when calling accountDetailsRetrieve");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Account-Token': x_account_token
      };
      let formParams = {
      };

      let authNames = ['tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AccountDetails;
      return this.apiClient.callApi(
        '/account-details', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
