/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SyncStatus from '../model/SyncStatus';

/**
* ForceResync service.
* @module api/ForceResyncApi
* @version 1.0
*/
export default class ForceResyncApi {

    /**
    * Constructs a new ForceResyncApi. 
    * @alias module:api/ForceResyncApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the syncStatusResyncCreate operation.
     * @callback module:api/ForceResyncApi~syncStatusResyncCreateCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/SyncStatus>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Force re-sync of all models. This is only available for organizations on Merge's Grow and Expand plans.
     * @param {String} x_account_token Token identifying the end user.
     * @param {module:api/ForceResyncApi~syncStatusResyncCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/SyncStatus>}
     */
    syncStatusResyncCreate(x_account_token, callback) {
      let postBody = null;
      // verify the required parameter 'x_account_token' is set
      if (x_account_token === undefined || x_account_token === null) {
        throw new Error("Missing the required parameter 'x_account_token' when calling syncStatusResyncCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'X-Account-Token': x_account_token
      };
      let formParams = {
      };

      let authNames = ['tokenAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [SyncStatus];
      return this.apiClient.callApi(
        '/sync-status/resync', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
