/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EndUserDetails from '../model/EndUserDetails';
import LinkToken from '../model/LinkToken';

/**
* LinkToken service.
* @module api/LinkTokenApi
* @version 1.0
*/
export default class LinkTokenApi {

    /**
    * Constructs a new LinkTokenApi. 
    * @alias module:api/LinkTokenApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the linkTokenCreate operation.
     * @callback module:api/LinkTokenApi~linkTokenCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LinkToken} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates a link token to be used when linking a new end user.
     * @param {module:model/EndUserDetails} endUserDetails 
     * @param {module:api/LinkTokenApi~linkTokenCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LinkToken}
     */
    linkTokenCreate(endUserDetails, callback) {
      let postBody = endUserDetails;
      // verify the required parameter 'endUserDetails' is set
      if (endUserDetails === undefined || endUserDetails === null) {
        throw new Error("Missing the required parameter 'endUserDetails' when calling linkTokenCreate");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['tokenAuth'];
      let contentTypes = ['application/json', 'application/x-www-form-urlencoded', 'multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = LinkToken;
      return this.apiClient.callApi(
        '/link-token', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
