/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeHrisApi);
  }
}(this, function(expect, MergeHrisApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeHrisApi.DataPassthroughRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DataPassthroughRequest', function() {
    it('should create an instance of DataPassthroughRequest', function() {
      // uncomment below and update the code to test DataPassthroughRequest
      //var instane = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be.a(MergeHrisApi.DataPassthroughRequest);
    });

    it('should have the property method (base name: "method")', function() {
      // uncomment below and update the code to test the property method
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property base_url_override (base name: "base_url_override")', function() {
      // uncomment below and update the code to test the property base_url_override
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property multipart_form_data (base name: "multipart_form_data")', function() {
      // uncomment below and update the code to test the property multipart_form_data
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property headers (base name: "headers")', function() {
      // uncomment below and update the code to test the property headers
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property request_format (base name: "request_format")', function() {
      // uncomment below and update the code to test the property request_format
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

    it('should have the property normalize_response (base name: "normalize_response")', function() {
      // uncomment below and update the code to test the property normalize_response
      //var instance = new MergeHrisApi.DataPassthroughRequest();
      //expect(instance).to.be();
    });

  });

}));
