/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeHrisApi);
  }
}(this, function(expect, MergeHrisApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeHrisApi.Employee();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Employee', function() {
    it('should create an instance of Employee', function() {
      // uncomment below and update the code to test Employee
      //var instane = new MergeHrisApi.Employee();
      //expect(instance).to.be.a(MergeHrisApi.Employee);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property displayFullName (base name: "display_full_name")', function() {
      // uncomment below and update the code to test the property displayFullName
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property workEmail (base name: "work_email")', function() {
      // uncomment below and update the code to test the property workEmail
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property personalEmail (base name: "personal_email")', function() {
      // uncomment below and update the code to test the property personalEmail
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property mobilePhoneNumber (base name: "mobile_phone_number")', function() {
      // uncomment below and update the code to test the property mobilePhoneNumber
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property employments (base name: "employments")', function() {
      // uncomment below and update the code to test the property employments
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property homeLocation (base name: "home_location")', function() {
      // uncomment below and update the code to test the property homeLocation
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property workLocation (base name: "work_location")', function() {
      // uncomment below and update the code to test the property workLocation
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property manager (base name: "manager")', function() {
      // uncomment below and update the code to test the property manager
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property team (base name: "team")', function() {
      // uncomment below and update the code to test the property team
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property ssn (base name: "ssn")', function() {
      // uncomment below and update the code to test the property ssn
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property ethnicity (base name: "ethnicity")', function() {
      // uncomment below and update the code to test the property ethnicity
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property maritalStatus (base name: "marital_status")', function() {
      // uncomment below and update the code to test the property maritalStatus
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "date_of_birth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property hireDate (base name: "hire_date")', function() {
      // uncomment below and update the code to test the property hireDate
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property employmentStatus (base name: "employment_status")', function() {
      // uncomment below and update the code to test the property employmentStatus
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property terminationDate (base name: "termination_date")', function() {
      // uncomment below and update the code to test the property terminationDate
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property avatar (base name: "avatar")', function() {
      // uncomment below and update the code to test the property avatar
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

    it('should have the property remoteData (base name: "remote_data")', function() {
      // uncomment below and update the code to test the property remoteData
      //var instance = new MergeHrisApi.Employee();
      //expect(instance).to.be();
    });

  });

}));
