/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeHrisApi);
  }
}(this, function(expect, MergeHrisApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeHrisApi.EmploymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmploymentRequest', function() {
    it('should create an instance of EmploymentRequest', function() {
      // uncomment below and update the code to test EmploymentRequest
      //var instane = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be.a(MergeHrisApi.EmploymentRequest);
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "job_title")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payRate (base name: "pay_rate")', function() {
      // uncomment below and update the code to test the property payRate
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payPeriod (base name: "pay_period")', function() {
      // uncomment below and update the code to test the property payPeriod
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payFrequency (base name: "pay_frequency")', function() {
      // uncomment below and update the code to test the property payFrequency
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payCurrency (base name: "pay_currency")', function() {
      // uncomment below and update the code to test the property payCurrency
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property flsaStatus (base name: "flsa_status")', function() {
      // uncomment below and update the code to test the property flsaStatus
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property effectiveDate (base name: "effective_date")', function() {
      // uncomment below and update the code to test the property effectiveDate
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property employmentType (base name: "employment_type")', function() {
      // uncomment below and update the code to test the property employmentType
      //var instance = new MergeHrisApi.EmploymentRequest();
      //expect(instance).to.be();
    });

  });

}));
