/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeHrisApi);
  }
}(this, function(expect, MergeHrisApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeHrisApi.EndUserDetailsRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EndUserDetailsRequest', function() {
    it('should create an instance of EndUserDetailsRequest', function() {
      // uncomment below and update the code to test EndUserDetailsRequest
      //var instane = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be.a(MergeHrisApi.EndUserDetailsRequest);
    });

    it('should have the property end_user_email_address (base name: "end_user_email_address")', function() {
      // uncomment below and update the code to test the property end_user_email_address
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property end_user_organization_name (base name: "end_user_organization_name")', function() {
      // uncomment below and update the code to test the property end_user_organization_name
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property end_user_origin_id (base name: "end_user_origin_id")', function() {
      // uncomment below and update the code to test the property end_user_origin_id
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property integration (base name: "integration")', function() {
      // uncomment below and update the code to test the property integration
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property link_expiry_mins (base name: "link_expiry_mins")', function() {
      // uncomment below and update the code to test the property link_expiry_mins
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

    it('should have the property should_create_magic_link_url (base name: "should_create_magic_link_url")', function() {
      // uncomment below and update the code to test the property should_create_magic_link_url
      //var instance = new MergeHrisApi.EndUserDetailsRequest();
      //expect(instance).to.be();
    });

  });

}));
