/**
 * Merge HRIS API
 * The unified API for building rich integrations with multiple HR Information System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeHrisApi);
  }
}(this, function(expect, MergeHrisApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeHrisApi.Location();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Location', function() {
    it('should create an instance of Location', function() {
      // uncomment below and update the code to test Location
      //var instane = new MergeHrisApi.Location();
      //expect(instance).to.be.a(MergeHrisApi.Location);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property remote_id (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remote_id
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property phone_number (base name: "phone_number")', function() {
      // uncomment below and update the code to test the property phone_number
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property street_1 (base name: "street_1")', function() {
      // uncomment below and update the code to test the property street_1
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property street_2 (base name: "street_2")', function() {
      // uncomment below and update the code to test the property street_2
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property zip_code (base name: "zip_code")', function() {
      // uncomment below and update the code to test the property zip_code
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property location_type (base name: "location_type")', function() {
      // uncomment below and update the code to test the property location_type
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property remote_data (base name: "remote_data")', function() {
      // uncomment below and update the code to test the property remote_data
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

    it('should have the property remote_was_deleted (base name: "remote_was_deleted")', function() {
      // uncomment below and update the code to test the property remote_was_deleted
      //var instance = new MergeHrisApi.Location();
      //expect(instance).to.be();
    });

  });

}));
